stages:
- build
- deploy

build-test:
  stage: build
  services:
  - mysql:5.7
  variables:
    MYSQL_DATABASE: "database_test"
    MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  tags:
  - web
  image: node:latest
  script:
  - npm install
  - npm run test
  only:
  - develop
  - /^([#|\d]+)-.*$/

deploy-master:
  stage: deploy
  image: deployer:latest
  tags:
  - web
  before_script:
  - apk update
  - apk add openssh
  script:
  - ssh ubuntu@gajiandulu-admin.projects.refactory.id -o StrictHostKeyChecking=no 'cd /home/ubuntu/apps/gajiandulu && bash -s' < deploy.sh
  only:
  - develop

