# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:latest
definitions:
          services:
            db:
              image: mysql
              environment:
                MYSQL_DATABASE: "database_test"
                MYSQL_ALLOW_EMPTY_PASSWORD: "true"

pipelines:
  default:
    - step:
        caches:
        - node
        deployment: test
        name: test
        script:
        - npm install
        - npm run test

  branches:
    master:
        - step:
              deployment: production
              script:
              - ssh ubuntu@api.gajiandulu.id -o StrictHostKeyChecking=no 'cd /home/ubuntu/apps/gajiandulu-api && bash -s' < deploy.sh
