const express = require('express');
const { auth } = require('@helpers');
const members = require('./members');
const companies = require('./companies');
const submissions = require('./submissions');
const presences = require('./presences');
const schedules = require('./schedules');
const register = require('./register');
const forgotPassword = require('./forgot-password');
const journals = require('./journals');
const shift = require('./shift');
const checklog = require('./checklog');
const transactions = require('./transactions');
const callback = require('./callback');
const packages = require('./packages');
const subscribements = require('./subscribements');
const promos = require('./promos');
const periodicPieces = require('./periodic-pieces');
const demo = require('./demo');
const divisions = require('./divisions');
const salaryGroups = require('./salary-groups');
const otp = require('./otp');

const v3 = express.Router();
v3.use('/register', register);
v3.use('/otp', otp);
v3.use('/demo', auth, demo);
v3.use('/members', auth, members);
v3.use('/companies', auth, companies);
v3.use('/submissions', auth, submissions);
v3.use('/presences', auth, presences);
v3.use('/schedules', auth, schedules);
v3.use('/forgot-password', forgotPassword);
v3.use('/journals', auth, journals);
v3.use('/shift', auth, shift);
v3.use('/checklog', auth, checklog);
v3.use('/transactions', auth, transactions);
v3.use('/callback', callback);
v3.use('/packages', auth, packages);
v3.use('/subscribements', auth, subscribements);
v3.use('/promos', auth, promos);
v3.use('/periodic-pieces', auth, periodicPieces);
v3.use('/divisions', auth, divisions);
v3.use('/salary-groups', auth, salaryGroups);

module.exports = v3;
