const EVENT = {
  SEND_WELCOME: 'sendWelcome',
  NEW_EMPLOYEE_JOINED: 'newEmployeeJoined',
  MEMBER_LATE_PRESENCE: 'memberLatePresence',
  MEMBER_OVERWORK: 'memberOverwork',
  WITHDRAW_APPROVED: 'withdrawAprroved',
  WITHDRAW_REJECTED: 'withdrawRejected',
  WITHDRAW_REQUEST: 'withdrawRequest',
  PERIODIC_PIECES: 'periodicPieces',
  CRON_SALARY_GROUP: 'cronSalaryGroup',
  SUBSCRIBING: 'subscribing',
  CRON_MEMBERS_SALARY_GROUP: 'cronMembersSalaryGroup',
  CRON_PAYROLL_DATE: 'cronPayrollDate',
  USER_ACTIVITY_NOTIF: 'userActivityNotif',
  MEMBER_APPROVED: 'memberApproved',
  CRON_MONTHLY_ALLOWANCE: 'cronMonthlyAllowance',
  CRON_CHANGE_EMPLOYEE_COMPANY_ID: 'cronChangeEmployeeCompanyId',
  SUBMISSION_APPROVAL: 'SubmissionApproval',
  SUBMISSION_ABORT: 'submissionAbort',
  ASK_SCHEDULE_SWAP: 'askScheduleSwap',
  SCHEDULE_SWAP_AGREEMENT: 'scheduleSwapAgreement',
  SCHEDULE_SWAP_APPROVAL: 'scheduleSwapApproval',
  GIVE_SCHEDULE_TO_TAKE_APPROVAL: 'giveScheduleToTakeApproval',
  TAKE_SCHEDULE: 'takeSchedule',
  PAYMENT: 'payment',
  CRON_PENDING_TRANSACTION: 'cronPendingTransaction',
  CRON_GET_BCA_TRANSFER: 'cronGetBcaTransfer',
  REJECT_MEMBER: 'rejectMember',
  WALKTROUGH_CHECKOUT: 'walktroughCheckout',
  SUBMISSION_CREATION: 'submissionCreation',
  CRON_PRESENCE: 'cronPresence'
};

module.exports = EVENT;
