module.exports = {
  MANAGER:
    'MEMBER_ADD,MEMBER_RESPONSE,MEMBER_SALARY_SIGHT,MEMBER_EDIT,MEMBER_DELETE,SCHEDULE_ADD,SCHEDULE_EDIT,SCHEDULE_DELETE,PRESENCE_ADD,PRESENCE_ADD_OWN_ID,PRESENCE_EDIT,PRESENCE_FULL_TIME_EDIT,PRESENCE_JOURNAL_EDIT,PRESENCE_NOTE_EDIT,PRESENCE_DELETE',
  SUPERVISOR:
    'MEMBER_SALARY_SIGHT,SCHEDULE_ADD,SCHEDULE_EDIT,SCHEDULE_DELETE,PRESENCE_ADD,PRESENCE_EDIT,PRESENCE_LIMITED_TIME_EDIT,PRESENCE_JOURNAL_EDIT,PRESENCE_NOTE_EDIT,PRESENCE_DELETE',
  OPERATOR:
    'SCHEDULE_ADD,PRESENCE_YEARLY_SIGHT,PRESENCE_ADD,PRESENCE_EDIT,PRESENCE_JOURNAL_EDIT,PRESENCE_NOTE_EDIT,PRESENCE_DELETE'
};
